#!/usr/bin/with-contenv sh

PLEX_PATH_USR="${PLEX_PATH_USR:-/usr/lib/plexmediaserver/}"

if [ ! -d "${PLEX_PATH_USR}" ]; then
    echo ""
    echo -e "\e[41m"
    echo -e " \e[1m[ERROR]\e[21m Plex binaries path not found! Run docker with the \"\e[1m-v <volume|path>:${PLEX_PATH_USR}\e[21m\" option"
    echo -e "\e[49m"
    echo ""
    exit 1
fi  
