#!/usr/bin/with-contenv sh
DATABASE_SQLITE_PATH="${DATABASE_SQLITE_PATH:-/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db}"

if [ ! -f "${DATABASE_SQLITE_PATH}" ]; then
    echo ""
    echo -e "\e[41m"
    echo -e " \e[1m[ERROR]\e[21m Plex SQLite database not found! Run docker with the \"\e[1m-v <volume|path>:${DATABASE_SQLITE_PATH}\e[21m\" option"
    echo -e "\e[49m"
    echo ""
    exit 1
fi  
